[workspace]
resolver = "3"
members = [
    "agora-http-parser",
    "agora-proxy"
]

[workspace.dependencies]
tokio = "1"

tracing = "0.1"
tracing-subscriber = "0.3"
http = "1.3.1"
regex = "1.12.2"

rstest = "0.26.1"
