[package]
name = "agora-proxy"
version = "0.1.0"
edition = "2024"

[dependencies] 
tokio = { workspace = true, features = ["net", "macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
