[package]
name = "agora-proxy"
version = "0.1.0"
edition = "2024"

[dependencies] 
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
agora-http-parser = {path = "../agora-http-parser"}
http.workspace = true
